let myjokes = [
  "Why don't scientists trust atoms? Because they make up everything!",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "What do you call a fish wearing a crown? King Neptune!",
  "Why couldn't the leopard play hide and seek? Because he was always spotted!",
  "I used to play piano by ear, but now I use my hands.",
  "Why don't oysters donate to charity? Because they are shellfish!",
  "What did the grape say when it got stepped on? Nothing, it just let out a little wine!",
  "I'm friends with 25 letters of the alphabet. I don't know why.",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
  "Why was the math book sad? Because it had too many problems.",
  "Why don't eggs tell jokes? Because they might crack up!",
  "I got a job at a bakery because I kneaded dough.",
  "How do you organize a space party? You planet!",
  "What did one wall say to the other wall? I'll meet you at the corner!",
  "What do you call a bear with no teeth? A gummy bear!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "Why did the tomato turn red? Because it saw the salad dressing!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "How do you make a tissue dance? You put a little boogie in it!",
  "I used to be a baker, but I couldn't make enough dough.",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why don't some couples go to the gym? Because some relationships don't work out!",
  "I told my wife she should embrace her mistakes. She hugged me.",
  "What's the best time to go to the dentist? Tooth-hurty!",
  "Why did the bicycle fall over? Because it was two-tired!",
  "Why don't some couples go to the gym? Because some relationships don't work out!",
  "How does a penguin build its house? Igloos it together!",
  "I just got a job at a bakery because I kneaded dough!",
  "What do you call fake spaghetti? An impasta!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "Why don't eggs tell jokes? Because they might crack up!",
  "How do you organize a space party? You planet!",
  "I'm friends with 25 letters of the alphabet. I don't know why.",
  "What do you call a bear with no teeth? A gummy bear!",
  "I used to play piano by ear, but now I use my hands.",
  "What do you call a fish wearing a crown? King Neptune!",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why did the tomato turn red? Because it saw the salad dressing!",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "What's the best time to go to the dentist? Tooth-hurty!",
  "Why couldn't the leopard play hide and seek? Because he was always spotted!",
  "Why did the bicycle fall over? Because it was two-tired!",
  "I used to be a baker, but I couldn't make enough dough.",
  "Why don't some couples go to the gym? Because some relationships don't work out!",
  "I told my wife she should embrace her mistakes. She hugged me.",
  "What do you call fake spaghetti? An impasta!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "Why don't eggs tell jokes? Because they might crack up!",
  "How do you organize a space party? You planet!",
  "I'm friends with 25 letters of the alphabet. I don't know why.",
  "What do you call a bear with no teeth? A gummy bear!",
  "I used to play piano by ear, but now I use my hands.",
  "What do you call a fish wearing a crown? King Neptune!",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why did the tomato turn red? Because it saw the salad dressing!",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "What's the best time to go to the dentist? Tooth-hurty!",
  "Why couldn't the leopard play hide and seek? Because he was always spotted!",
  "Why did the bicycle fall over? Because it was two-tired!",
  "I used to be a baker, but I couldn't make enough dough.",
  "Why don't some couples go to the gym? Because some relationships don't work out!",
  "I told my wife she should embrace her mistakes. She hugged me.",
  "What do you call fake spaghetti? An impasta!",
  "Why don't skeletons fight each other? They don't have the guts!",
  "Why don't eggs tell jokes? Because they might crack up!",
  "How do you organize a space party? You planet!",
  "I'm friends with 25 letters of the alphabet. I don't know why.",
  "What do you call a bear with no teeth? A gummy bear!",
  "I used to play piano by ear, but now I use my hands.",
  "What do you call a fish wearing a crown? King Neptune!",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "Why did the tomato turn red? Because it saw the salad dressing!",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "What's the best time to go to the dentist? Tooth-hurty!",
  "Why couldn't the leopard play hide and seek? Because he was always spotted!",
  "Why did the bicycle fall over? Because it was two-tired!",
  "I used to be a baker, but I couldn't make enough dough.",
  "Why don't some couples go to the gym? Because some relationships don't work out!",
  "I told my wife she should embrace her mistakes. She hugged me.",
  "What do you call fake spaghetti? An impasta!",
];
function saurav(){
let index = Math.floor(Math.random() * myjokes.length);
document.getElementsByClassName("joke")[0].innerHTML= myjokes[index]
}


